name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

permissions:
  contents: write
  pull-requests: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHP-CS-Fixer
        run: composer format

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Fix styling
          title: 'Fix PHP code style issues'
          body: |
            This PR fixes PHP code style issues found by PHP-CS-Fixer.
            
            - Applied PHP-CS-Fixer rules
            - Automated formatting corrections
          branch: fix/code-style-${{ github.run_number }}
          delete-branch: true
